const BUY_VANILLA_CAKE = "BUY VANILLA CAKE";
const REFUND_VANILLA_CAKE = "REFUND VANILLA CAKE";

const BUY_CHOCO_CAKE = "BUY CHOCO CAKE";
const REFUND_CHOCO_CAKE = "REFUND CHOCO CAKE";

export {
    BUY_VANILLA_CAKE,
    REFUND_VANILLA_CAKE,
    BUY_CHOCO_CAKE,
    REFUND_CHOCO_CAKE,
}